language: java
jdk:
  - oraclejdk8
env:
  - SERVER=payara
  - SERVER=wildfly
  - SERVER=glassfish
  - SERVER=tomee
  - SERVER=liberty
script: mvn clean package -P $SERVER

deploy:
   provider: script
   script: mvn deploy -Dmaven.test.skip -s settings.xml
   on:
      branch: develop
      condition: $SERVER = wildfly